news_collection:
  enabled: True
  output_json_file: "scraped_api_news_articles.json" 

news_api_config:
  enable_api_collection: True 
  delay_between_api_requests_seconds: 3 
  random_delay_range_seconds: 1
  output_filename: "scraped_api_news_articles.json" 

  target_tickers: ["NVDA", "AAPL", "MSFT", "TSLA", "AMD"]

  gemini_config:
    enabled: True 
    api_key_env_var: "GEMINI_API_KEY"
    model_name: "gemini-pro" 
    generation_config:
      temperature: 0.7
      top_p: 1.0
      top_k: 40
      max_output_tokens: 2048
    safety_settings:
      - category: "HARM_CATEGORY_HARASSMENT"
        threshold: "BLOCK_NONE"
      - category: "HARM_CATEGORY_HATE_SPEECH"
        threshold: "BLOCK_NONE"
      - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
        threshold: "BLOCK_NONE"
      - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
        threshold: "BLOCK_NONE"

  apis:
    - name: "AlphaVantage"
      type: "financial_news"
      api_key_env_var: "ALPHA_VANTAGE_API_KEY"
      base_url: "https://www.alphavantage.co/query"
      endpoint_params:
        function: "NEWS_SENTIMENT"
        sort: "LATEST"
        limit: 1000 

    - name: "Finnhub"
      type: "financial_news"
      api_key_env_var: "FINNHUB_API_KEY"
      base_url: "https://finnhub.io/api/v1/news"
      endpoint_params:
        category: "general"

    - name: "NewsAPI"
      type: "general_news"
      api_key_env_var: "NEWS_API_KEY"
      base_url: "https://newsapi.org/v2/everything" 
      endpoint_params:
        q: "stock market OR economy OR inflation OR interest rates" 
        language: "en"
        pageSize: 100 # NewsAPI 무료 플랜은 pageSize 최대 100개입니다.
        sortBy: "publishedAt" 
        # 참고: NewsAPI 무료 플랜은 최근 30일 데이터만 지원하며, 과거 데이터는 지원하지 않습니다.
        # from: "2025-06-12T00:00:00Z" # 예시: 1개월 전부터 (main_collector.py에서 동적으로 설정)
        # to: "2025-07-12T23:59:59Z"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

    - name: "NewsData_io"
      type: "general_news_with_content"
      api_key_env_var: "NEWSDATA_IO_API_KEY"
      base_url: "https://newsdata.io/api/1/news"
      endpoint_params:
        q: "investment OR finance OR technology" 
        language: "en"
        country: "us" 
        # full_content: "1" # <-- ***이 줄은 제거되었습니다. 422 오류의 원인.***
        # 참고: NewsData.io도 무료 플랜에서 긴 과거 데이터는 지원하지 않을 것입니다.
        # from_date: "2025-06-12" # 예시: 1개월 전부터 (main_collector.py에서 동적으로 설정)
        # to_date: "2025-07-12"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

# 뉴스 처리 설정
news_processing:
  enabled: True # 뉴스 처리 활성화 여부

# 뉴스 분석 및 시각화 설정
news_analysis:
  enabled: True # 뉴스 분석 및 시각화 활성화 여부
  output_image_dir: "visualizations" # 시각화 이미지 저장 디렉토리 (프로젝트 루트 아래)
  top_n_topics_wordcloud: 50 # 워드 클라우드에 표시할 상위 주제 개수
  top_n_tickers_pie_charts: 5 # 파이 차트로 표시할 상위 티커 개수
  sentiment_analysis_interval: "D" # 시계열 감성 분석 간격 ('D': 일별, 'W': 주별, 'M': 월별)