# news_sources.yaml

# 뉴스 수집 활성화 및 출력 파일 설정
news_collection:
  enabled: True
  # 수집된 API 뉴스 저장 파일명 (news_api_config.output_filename과 통일)
  output_json_file: "scraped_api_news_articles.json" 

# API별 상세 수집 설정
news_api_config:
  enable_api_collection: True 

  delay_between_api_requests_seconds: 3 # 각 API 호출 간 최소 딜레이 (초)
  random_delay_range_seconds: 1 # 딜레이에 추가할 무작위 범위 (예: 3 + 0~1초)
  
  # 수집된 데이터 저장 설정 (news_collection.output_json_file과 통일)
  output_filename: "scraped_api_news_articles.json" 

  apis:
    - name: "AlphaVantage"
      type: "financial_news"
      api_key_env_var: "ALPHA_VANTAGE_API_KEY"
      base_url: "https://www.alphavantage.co/query"
      endpoint_params:
        function: "NEWS_SENTIMENT"
        sort: "LATEST"
        limit: 1000 # 한 번에 가져올 기사 수 (API 제한 확인 필요)
        # 참고: AlphaVantage 무료 플랜은 보통 최근 데이터만 지원하거나 시간 범위 제한이 있습니다.
        # time_from: "20250612T0000" # 예시: 1개월 전부터
        # time_to: "20250712T2359"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

    - name: "Finnhub"
      type: "financial_news"
      api_key_env_var: "FINNHUB_API_KEY"
      base_url: "https://finnhub.io/api/v1/news"
      endpoint_params:
        category: "general"
        # 참고: Finnhub 무료 플랜은 보통 최근 데이터만 지원합니다.
        # from: "2025-06-12" # 예시: 1개월 전부터
        # to: "2025-07-12"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

    - name: "NewsAPI"
      type: "general_news"
      api_key_env_var: "NEWS_API_KEY"
      base_url: "https://newsapi.org/v2/everything" 
      endpoint_params:
        q: "stock market OR economy OR inflation OR interest rates" 
        language: "en"
        pageSize: 100 # NewsAPI 무료 플랜은 pageSize 최대 100개입니다.
        sortBy: "publishedAt" 
        # 참고: NewsAPI 무료 플랜은 최근 30일 데이터만 지원하며, 과거 데이터는 지원하지 않습니다.
        # from: "2025-06-12T00:00:00Z" # 예시: 1개월 전부터 (main_collector.py에서 동적으로 설정)
        # to: "2025-07-12T23:59:59Z"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

    - name: "NewsData_io"
      type: "general_news_with_content"
      api_key_env_var: "NEWSDATA_IO_API_KEY"
      base_url: "https://newsdata.io/api/1/news"
      endpoint_params:
        q: "investment OR finance OR technology" 
        language: "en"
        country: "us" 
        # full_content: "1" # <-- ***이 줄은 제거되었습니다. 422 오류의 원인.***
        # 참고: NewsData.io도 무료 플랜에서 긴 과거 데이터는 지원하지 않을 것입니다.
        # from_date: "2025-06-12" # 예시: 1개월 전부터 (main_collector.py에서 동적으로 설정)
        # to_date: "2025-07-12"   # 현재 날짜 (main_collector.py에서 동적으로 설정)

# 뉴스 처리 설정
news_processing:
  enabled: True # 뉴스 처리 활성화 여부

# 뉴스 분석 및 시각화 설정
news_analysis:
  enabled: True # 뉴스 분석 및 시각화 활성화 여부
  output_image_dir: "visualizations" # 시각화 이미지 저장 디렉토리 (프로젝트 루트 아래)
  top_n_topics_wordcloud: 50 # 워드 클라우드에 표시할 상위 주제 개수
  top_n_tickers_pie_charts: 5 # 파이 차트로 표시할 상위 티커 개수
  sentiment_analysis_interval: "D" # 시계열 감성 분석 간격 ('D': 일별, 'W': 주별, 'M': 월별)